### PR TITLE
Implement better theme switcher

### PR DESCRIPTION
**Pull request by queengooborg**
This PR implements a better theme switcher into the website, allowing a user to select "OS Setting", as well as mitigating the small delay in embedding the element causing the screen to flash for a moment.

This also effectively reverts #8 which took away this logic altogether.  The reason for this is because the value of `prefers-color-scheme` is not always what the user would actually want, especially for Chrome Linux users where the media query is broken altogether.

### CODE REVIEW

**Comment by queengooborg** [comment]
CC @wbamberg

**Comment by wbamberg** [comment]
This doesn't work for me: selecting "Dark" when I'm in light theme doesn't do anything (Chrome or Firefox).

Also when I hover over the button, I suddenly get a horizontal scrollbar in the whole page.

I think if we have to have this, we should put it in the footer. It's a thing which some people will have to use a small number of times, and it's not content like the other items in the nav.

**Comment by queengooborg** [comment]
> I suddenly get a horizontal scrollbar in the whole page.

My bad -- I tested how it would look on smaller screens, but forgot to test it on larger screens!  I'll implement a fix soon!

> I think if we have to have this, we should put it in the footer. It's a thing which some people will have to use a small number of times, and it's not content like the other items in the nav.

I left it up in the navbar since that is also what MDN Web Docs does, and leaving it towards the top makes it more visible.  If a user comes to a linked page on the website with a lot of content, such as the impact reports, then they won't know they can switch the theme until they've finished reading the page (which, as I alluded to before, can create a negative experience for some users).  I agree that its current placement and styling makes it seem like another link, even without the underline.  Let me see what I can do!

> This doesn't work for me: selecting "Dark" when I'm in light theme doesn't do anything (Chrome or Firefox).

This is working fine on my end, though I have a dark-by-default OS preference.  Are there any console errors?

**Comment by wbamberg** [comment]
Screen Shot 2022-08-24 at 9 08 05 AM

...also I wasn't sure if it's intentional for the currently-selected option to be very low-contrast when you hover it on dark mode:

Screen Shot 2022-08-24 at 9 10 30 AM

Also it looks like the menu right hand side is getting cut off, so we only get rounded corners on the left side, is that right?

Screen Shot 2022-08-24 at 9 12 34 AM

Just a detail though.

**Comment by queengooborg** [comment]
> Also it looks like the menu right hand side is getting cut off, so we only get rounded corners on the left side, is that right?

I've tweaked the menu so that "OS Default" is now "Auto", thus mitigating the issue since the menu is smaller than the word "Theme"!

> But the site logo color isn't getting switched in dark mode

This was a small bug in the image switcher that occurs when you switch from light theme to light theme again; this has now been fixed!

**Comment by wbamberg** [comment]
Still a problem switching from "Dark" to "Auto":

theme-switcher

**Comment by queengooborg** [comment]
Looks like that bug was due to switching from Dark to Auto-Light, luckily (after burning my eyes with a system light theme, hiss) I was able to fix it, so this is now ready to go!

**Review by wbamberg — APPROVED** [review]
Thanks!

**Pull request merged**
