### PR TITLE
Create florian-owd-director.md

### PR DESCRIPTION
**Pull request by jorydotcom**

### CODE REVIEW

**Comment by jorydotcom** [comment]
@Elchi3 I can't download your pic from the Google Doc for some reason, and the screenshot version is not good quality. Can you add the .png to the assets directory for me?

**Comment by Elchi3** [comment]
@jorydotcom Thanks for writing this! 💚 Added my photo!

**Review by wbamberg — APPROVED** [review]
🎉

**Review by captainbrosset — APPROVED** [review]

**Review by Elchi3 — APPROVED** [review]
Yay!

**Pull request merged**
